[package]
name = "rate-limiter"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
tokio = {version = "1.39.2", features = ["time", "rt", "rt-multi-thread", "macros"]}

[[example]]
name = "tokio-demo"